name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'version.txt'
      - '.github/workflows/docker-build-push.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for tags
      
      - name: Get cfn-lint version
        id: get-version
        run: echo "CFN_LINT_VERSION=$(cat version.txt)" >> $GITHUB_OUTPUT
        
      - name: Create GitHub Tag
        if: github.event_name != 'pull_request'
        run: |
          VERSION=${{ steps.get-version.outputs.CFN_LINT_VERSION }}
          
          # Check if tag already exists
          if ! git ls-remote --tags origin | grep -q "refs/tags/v${VERSION}$"; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git tag -a "v${VERSION}" -m "Release v${VERSION} - cfn-lint version ${VERSION}"
            git push origin "v${VERSION}"
            echo "Created and pushed tag v${VERSION}"
          else
            echo "Tag v${VERSION} already exists, skipping tag creation"
          fi
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            CFN_LINT_VERSION=${{ steps.get-version.outputs.CFN_LINT_VERSION }}
          tags: |
            klahnen/cfn-lint:latest
            klahnen/cfn-lint:${{ steps.get-version.outputs.CFN_LINT_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
